name: Build Docker Image and Upload as Artifact

on:
  workflow_dispatch:  # Allows you to trigger it manually

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: |
        docker build -t myimage:latest .

    - name: Save Docker image to tar
      run: |
        docker save myimage:latest -o myimage.tar

    - name: Upload image as artifact
      uses: actions/upload-artifact@v4
      with:
        name: docker-image-tar
        path: myimage.tar
